# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:05:40+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SourceInstanceTier(Enum):
    TIER_UNSPECIFIED = 'TIER_UNSPECIFIED'
    STANDARD = 'STANDARD'
    PREMIUM = 'PREMIUM'
    BASIC_HDD = 'BASIC_HDD'
    BASIC_SSD = 'BASIC_SSD'
    HIGH_SCALE_SSD = 'HIGH_SCALE_SSD'
    ENTERPRISE = 'ENTERPRISE'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    FINALIZING = 'FINALIZING'
    READY = 'READY'
    DELETING = 'DELETING'
    INVALID = 'INVALID'


class Backup(BaseModel):
    capacityGb: Optional[str] = Field(
        None,
        description='Output only. Capacity of the source file share when the backup was created.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. The time when the backup was created.'
    )
    description: Optional[str] = Field(
        None,
        description='A description of the backup with 2048 characters or less. Requests with longer descriptions will be rejected.',
    )
    downloadBytes: Optional[str] = Field(
        None,
        description='Output only. Amount of bytes that will be downloaded if the backup is restored. This may be different than storage bytes, since sequential backups of the same disk will share storage.',
    )
    kmsKey: Optional[str] = Field(
        None, description='Immutable. KMS key name used for data encryption.'
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Resource labels to represent user provided metadata.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of the backup, in the format `projects/{project_number}/locations/{location_id}/backups/{backup_id}`.',
    )
    satisfiesPzs: Optional[bool] = Field(
        None, description='Output only. Reserved for future use.'
    )
    sourceFileShare: Optional[str] = Field(
        None,
        description='Name of the file share in the source Filestore instance that the backup is created from.',
    )
    sourceInstance: Optional[str] = Field(
        None,
        description='The resource name of the source Filestore instance, in the format `projects/{project_number}/locations/{location_id}/instances/{instance_id}`, used to create this backup.',
    )
    sourceInstanceTier: Optional[SourceInstanceTier] = Field(
        None,
        description='Output only. The service tier of the source Filestore instance that this backup is created from.',
    )
    state: Optional[State] = Field(None, description='Output only. The backup state.')
    storageBytes: Optional[str] = Field(
        None,
        description='Output only. The size of the storage used by the backup. As backups share storage, this number is expected to change with backup creation/deletion.',
    )


class CancelOperationRequest(BaseModel):
    pass


class Date(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class Empty(BaseModel):
    pass


class State1(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    READY = 'READY'
    UPDATING = 'UPDATING'
    REPAIRING = 'REPAIRING'
    DELETING = 'DELETING'
    ERROR = 'ERROR'


class GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule(BaseModel):
    canReschedule: Optional[bool] = Field(
        None,
        description='This field is deprecated, and will be always set to true since reschedule can happen multiple times now. This field should not be removed until all service producers remove this for their customers.',
    )
    endTime: Optional[str] = Field(
        None, description='The scheduled end time for the maintenance.'
    )
    rolloutManagementPolicy: Optional[str] = Field(
        None,
        description='The rollout management policy this maintenance schedule is associated with. When doing reschedule update request, the reschedule should be against this given policy.',
    )
    scheduleDeadlineTime: Optional[str] = Field(
        None,
        description="schedule_deadline_time is the time deadline any schedule start time cannot go beyond, including reschedule. It's normally the initial schedule start time plus maintenance window length (1 day or 1 week). Maintenance cannot be scheduled to start beyond this deadline.",
    )
    startTime: Optional[str] = Field(
        None, description='The scheduled start time for the maintenance.'
    )


class GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter(BaseModel):
    values: Optional[List[str]] = Field(
        None,
        description="Optional. Array of string values. e.g. instance's replica information.",
    )


class GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource(BaseModel):
    resourceType: Optional[str] = Field(
        None,
        description="Type of the resource. This can be either a GCP resource or a custom one (e.g. another cloud provider's VM). For GCP compute resources use singular form of the names listed in GCP compute API documentation (https://cloud.google.com/compute/docs/reference/rest/v1/), prefixed with 'compute-', for example: 'compute-instance', 'compute-disk', 'compute-autoscaler'.",
    )
    resourceUrl: Optional[str] = Field(
        None,
        description='URL identifying the resource, e.g. "https://www.googleapis.com/compute/v1/projects/...)".',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility(BaseModel):
    eligible: Optional[bool] = Field(
        None, description='Whether an instance is eligible or ineligible.'
    )
    reason: Optional[str] = Field(
        None,
        description='User-defined reason for the current value of instance eligibility. Usually, this can be directly mapped to the internal state. An empty reason is allowed.',
    )


class State2(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    READY = 'READY'
    REPAIRING = 'REPAIRING'
    DELETING = 'DELETING'
    ERROR = 'ERROR'
    RESTORING = 'RESTORING'
    SUSPENDED = 'SUSPENDED'
    SUSPENDING = 'SUSPENDING'
    RESUMING = 'RESUMING'
    REVERTING = 'REVERTING'


class SuspensionReason(Enum):
    SUSPENSION_REASON_UNSPECIFIED = 'SUSPENSION_REASON_UNSPECIFIED'
    KMS_KEY_ISSUE = 'KMS_KEY_ISSUE'


class Tier(Enum):
    TIER_UNSPECIFIED = 'TIER_UNSPECIFIED'
    STANDARD = 'STANDARD'
    PREMIUM = 'PREMIUM'
    BASIC_HDD = 'BASIC_HDD'
    BASIC_SSD = 'BASIC_SSD'
    HIGH_SCALE_SSD = 'HIGH_SCALE_SSD'
    ENTERPRISE = 'ENTERPRISE'


class ListBackupsResponse(BaseModel):
    backups: Optional[List[Backup]] = Field(
        None,
        description='A list of backups in the project for the specified location. If the `{location}` value in the request is "-", the response contains a list of backups from all locations. If any location is unreachable, the response will only return backups in reachable locations and the "unreachable" field will be populated with a list of unreachable locations.',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='The token you can use to retrieve the next page of results. Not returned if there are no more results in the list.',
    )
    unreachable: Optional[List[str]] = Field(
        None, description='Locations that could not be reached.'
    )


class Location(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The friendly name for this location, typically a nearby city name. For example, "Tokyo".',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Cross-service attributes for the location. For example {"cloud.googleapis.com/region": "us-east1"}',
    )
    locationId: Optional[str] = Field(
        None,
        description='The canonical id for this location. For example: `"us-east1"`.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata. For example the available capacity at the given location.',
    )
    name: Optional[str] = Field(
        None,
        description='Resource name for the location, which may vary between implementations. For example: `"projects/example-project/locations/us-east1"`',
    )


class State3(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    READY = 'READY'
    DELETING = 'DELETING'


class ConnectMode(Enum):
    CONNECT_MODE_UNSPECIFIED = 'CONNECT_MODE_UNSPECIFIED'
    DIRECT_PEERING = 'DIRECT_PEERING'
    PRIVATE_SERVICE_ACCESS = 'PRIVATE_SERVICE_ACCESS'


class Mode(Enum):
    ADDRESS_MODE_UNSPECIFIED = 'ADDRESS_MODE_UNSPECIFIED'
    MODE_IPV4 = 'MODE_IPV4'


class NetworkConfig(BaseModel):
    connectMode: Optional[ConnectMode] = Field(
        None,
        description='The network connect mode of the Filestore instance. If not provided, the connect mode defaults to DIRECT_PEERING.',
    )
    ipAddresses: Optional[List[str]] = Field(
        None,
        description='Output only. IPv4 addresses in the format `{octet1}.{octet2}.{octet3}.{octet4}` or IPv6 addresses in the format `{block1}:{block2}:{block3}:{block4}:{block5}:{block6}:{block7}:{block8}`.',
    )
    modes: Optional[List[Mode]] = Field(
        None,
        description='Internet protocol versions for which the instance has IP addresses assigned. For this version, only MODE_IPV4 is supported.',
    )
    network: Optional[str] = Field(
        None,
        description='The name of the Google Compute Engine [VPC network](https://cloud.google.com/vpc/docs/vpc) to which the instance is connected.',
    )
    reservedIpRange: Optional[str] = Field(
        None,
        description="Optional, reserved_ip_range can have one of the following two types of values. * CIDR range value when using DIRECT_PEERING connect mode. * [Allocated IP address range](https://cloud.google.com/compute/docs/ip-addresses/reserve-static-internal-ip-address) when using PRIVATE_SERVICE_ACCESS connect mode. When the name of an allocated IP address range is specified, it must be one of the ranges associated with the private service access connection. When specified as a direct CIDR value, it must be a /29 CIDR block for Basic tier, a /24 CIDR block for High Scale tier, or a /26 CIDR block for Enterprise tier in one of the [internal IP address ranges](https://www.arin.net/reference/research/statistics/address_filters/) that identifies the range of IP addresses reserved for this instance. For example, 10.0.0.0/29, 192.168.0.0/24 or 192.168.0.0/26, respectively. The range you specify can't overlap with either existing subnets or assigned IP address ranges for other Filestore instances in the selected VPC network.",
    )


class AccessMode(Enum):
    ACCESS_MODE_UNSPECIFIED = 'ACCESS_MODE_UNSPECIFIED'
    READ_ONLY = 'READ_ONLY'
    READ_WRITE = 'READ_WRITE'


class SquashMode(Enum):
    SQUASH_MODE_UNSPECIFIED = 'SQUASH_MODE_UNSPECIFIED'
    NO_ROOT_SQUASH = 'NO_ROOT_SQUASH'
    ROOT_SQUASH = 'ROOT_SQUASH'


class NfsExportOptions(BaseModel):
    accessMode: Optional[AccessMode] = Field(
        None,
        description='Either READ_ONLY, for allowing only read requests on the exported directory, or READ_WRITE, for allowing both read and write requests. The default is READ_WRITE.',
    )
    anonGid: Optional[str] = Field(
        None,
        description='An integer representing the anonymous group id with a default value of 65534. Anon_gid may only be set with squash_mode of ROOT_SQUASH. An error will be returned if this field is specified for other squash_mode settings.',
    )
    anonUid: Optional[str] = Field(
        None,
        description='An integer representing the anonymous user id with a default value of 65534. Anon_uid may only be set with squash_mode of ROOT_SQUASH. An error will be returned if this field is specified for other squash_mode settings.',
    )
    ipRanges: Optional[List[str]] = Field(
        None,
        description='List of either an IPv4 addresses in the format `{octet1}.{octet2}.{octet3}.{octet4}` or CIDR ranges in the format `{octet1}.{octet2}.{octet3}.{octet4}/{mask size}` which may mount the file share. Overlapping IP ranges are not allowed, both within and across NfsExportOptions. An error will be returned. The limit is 64 IP ranges/addresses for each FileShareConfig among all NfsExportOptions.',
    )
    squashMode: Optional[SquashMode] = Field(
        None,
        description='Either NO_ROOT_SQUASH, for allowing root access on the exported directory, or ROOT_SQUASH, for not allowing root access. The default is NO_ROOT_SQUASH.',
    )


class OperationMetadata(BaseModel):
    apiVersion: Optional[str] = Field(
        None, description='Output only. API version used to start the operation.'
    )
    cancelRequested: Optional[bool] = Field(
        None,
        description='Output only. Identifies whether the user has requested cancellation of the operation. Operations that have been cancelled successfully have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. The time the operation was created.'
    )
    endTime: Optional[str] = Field(
        None, description='Output only. The time the operation finished running.'
    )
    statusDetail: Optional[str] = Field(
        None, description='Output only. Human-readable status of the operation, if any.'
    )
    target: Optional[str] = Field(
        None,
        description='Output only. Server-defined resource path for the target of the operation.',
    )
    verb: Optional[str] = Field(
        None, description='Output only. Name of the verb executed by the operation.'
    )


class RestoreInstanceRequest(BaseModel):
    fileShare: Optional[str] = Field(
        None,
        description='Required. Name of the file share in the Filestore instance that the backup is being restored to.',
    )
    sourceBackup: Optional[str] = Field(
        None,
        description='The resource name of the backup, in the format `projects/{project_number}/locations/{location_id}/backups/{backup_id}`.',
    )


class RevertInstanceRequest(BaseModel):
    targetSnapshotId: Optional[str] = Field(
        None,
        description="Required. The snapshot resource ID, in the format 'my-snapshot', where the specified ID is the {snapshot_id} of the fully qualified name like projects/{project_id}/locations/{location_id}/instances/{instance_id}/snapshots/{snapshot_id}",
    )


class Day(Enum):
    DAY_OF_WEEK_UNSPECIFIED = 'DAY_OF_WEEK_UNSPECIFIED'
    MONDAY = 'MONDAY'
    TUESDAY = 'TUESDAY'
    WEDNESDAY = 'WEDNESDAY'
    THURSDAY = 'THURSDAY'
    FRIDAY = 'FRIDAY'
    SATURDAY = 'SATURDAY'
    SUNDAY = 'SUNDAY'


class State4(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    READY = 'READY'
    DELETING = 'DELETING'


class Snapshot(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. The time when the snapshot was created.'
    )
    description: Optional[str] = Field(
        None,
        description='A description of the snapshot with 2048 characters or less. Requests with longer descriptions will be rejected.',
    )
    filesystemUsedBytes: Optional[str] = Field(
        None,
        description='Output only. The amount of bytes needed to allocate a full copy of the snapshot content',
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Resource labels to represent user provided metadata.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of the snapshot, in the format `projects/{project_id}/locations/{location_id}/instances/{instance_id}/snapshots/{snapshot_id}`.',
    )
    state: Optional[State4] = Field(
        None, description='Output only. The snapshot state.'
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TimeOfDay(BaseModel):
    hours: Optional[int] = Field(
        None,
        description='Hours of day in 24 hour format. Should be from 0 to 23. An API may choose to allow the value "24:00:00" for scenarios like business closing time.',
    )
    minutes: Optional[int] = Field(
        None, description='Minutes of hour of day. Must be from 0 to 59.'
    )
    nanos: Optional[int] = Field(
        None,
        description='Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.',
    )
    seconds: Optional[int] = Field(
        None,
        description='Seconds of minutes of the time. Must normally be from 0 to 59. An API may allow the value 60 if it allows leap-seconds.',
    )


class Channel(Enum):
    UPDATE_CHANNEL_UNSPECIFIED = 'UPDATE_CHANNEL_UNSPECIFIED'
    EARLIER = 'EARLIER'
    LATER = 'LATER'
    WEEK1 = 'WEEK1'
    WEEK2 = 'WEEK2'
    WEEK5 = 'WEEK5'


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class DailyCycle(BaseModel):
    duration: Optional[str] = Field(
        None,
        description='Output only. Duration of the time window, set by service producer.',
    )
    startTime: Optional[TimeOfDay] = Field(
        None, description='Time within the day to start the operations.'
    )


class DenyMaintenancePeriod(BaseModel):
    endDate: Optional[Date] = Field(
        None,
        description='Deny period end date. This can be: * A full date, with non-zero year, month and day values. * A month and day value, with a zero year. Allows recurring deny periods each year. Date matching this period will have to be before the end.',
    )
    startDate: Optional[Date] = Field(
        None,
        description='Deny period start date. This can be: * A full date, with non-zero year, month and day values. * A month and day value, with a zero year. Allows recurring deny periods each year. Date matching this period will have to be the same or after the start.',
    )
    time: Optional[TimeOfDay] = Field(
        None,
        description='Time in UTC when the Blackout period starts on start_date and ends on end_date. This can be: * Full time. * All zeros for 00:00:00 UTC',
    )


class FileShareConfig(BaseModel):
    capacityGb: Optional[str] = Field(
        None,
        description='File share capacity in gigabytes (GB). Filestore defines 1 GB as 1024^3 bytes.',
    )
    name: Optional[str] = Field(
        None, description='The name of the file share (must be 16 characters or less).'
    )
    nfsExportOptions: Optional[List[NfsExportOptions]] = Field(
        None,
        description='Nfs Export Options. There is a limit of 10 export options per file share.',
    )
    sourceBackup: Optional[str] = Field(
        None,
        description='The resource name of the backup, in the format `projects/{project_number}/locations/{location_id}/backups/{backup_id}`, that this file share has been restored from.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility(BaseModel):
    eligibilities: Optional[
        Dict[str, GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility]
    ] = Field(
        None,
        description='An entry in the eligibilities map specifies an eligibility for a particular SLI for the given instance. The SLI key in the name must be a valid SLI name specified in the Eligibility Exporter binary flags otherwise an error will be emitted by Eligibility Exporter and the oncaller will be alerted. If an SLI has been defined in the binary flags but the eligibilities map does not contain it, the corresponding SLI time series will not be emitted by the Eligibility Exporter. This ensures a smooth rollout and compatibility between the data produced by different versions of the Eligibility Exporters. If eligibilities map contains a key for an SLI which has not been declared in the binary flags, there will be an error message emitted in the Eligibility Exporter log and the metric for the SLI in question will not be emitted.',
    )


class Instance(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. The time when the instance was created.'
    )
    description: Optional[str] = Field(
        None, description='The description of the instance (2048 characters or less).'
    )
    etag: Optional[str] = Field(
        None,
        description='Server-specified ETag for the instance resource to prevent simultaneous updates from overwriting each other.',
    )
    fileShares: Optional[List[FileShareConfig]] = Field(
        None,
        description='File system shares on the instance. For this version, only a single file share is supported.',
    )
    kmsKeyName: Optional[str] = Field(
        None, description='KMS key name used for data encryption.'
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Resource labels to represent user provided metadata.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of the instance, in the format `projects/{project}/locations/{location}/instances/{instance}`.',
    )
    networks: Optional[List[NetworkConfig]] = Field(
        None,
        description='VPC networks to which the instance is connected. For this version, only a single network is supported.',
    )
    satisfiesPzs: Optional[bool] = Field(
        None, description='Output only. Reserved for future use.'
    )
    state: Optional[State2] = Field(
        None, description='Output only. The instance state.'
    )
    statusMessage: Optional[str] = Field(
        None,
        description='Output only. Additional information about the instance state, if available.',
    )
    suspensionReasons: Optional[List[SuspensionReason]] = Field(
        None,
        description='Output only. Field indicates all the reasons the instance is in "SUSPENDED" state.',
    )
    tier: Optional[Tier] = Field(None, description='The service tier of the instance.')


class ListInstancesResponse(BaseModel):
    instances: Optional[List[Instance]] = Field(
        None,
        description='A list of instances in the project for the specified location. If the `{location}` value in the request is "-", the response contains a list of instances from all locations. If any location is unreachable, the response will only return instances in reachable locations and the "unreachable" field will be populated with a list of unreachable locations.',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='The token you can use to retrieve the next page of results. Not returned if there are no more results in the list.',
    )
    unreachable: Optional[List[str]] = Field(
        None, description='Locations that could not be reached.'
    )


class ListLocationsResponse(BaseModel):
    locations: Optional[List[Location]] = Field(
        None,
        description='A list of locations that matches the specified filter in the request.',
    )
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )


class ListSnapshotsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='The token you can use to retrieve the next page of results. Not returned if there are no more results in the list.',
    )
    snapshots: Optional[List[Snapshot]] = Field(
        None,
        description='A list of snapshots in the project for the specified instance.',
    )


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class Schedule(BaseModel):
    day: Optional[Day] = Field(
        None,
        description='Allows to define schedule that runs specified day of the week.',
    )
    duration: Optional[str] = Field(
        None,
        description='Output only. Duration of the time window, set by service producer.',
    )
    startTime: Optional[TimeOfDay] = Field(
        None, description='Time within the window to start the operations.'
    )


class WeeklyCycle(BaseModel):
    schedule: Optional[List[Schedule]] = Field(
        None,
        description='User can specify multiple windows in a week. Minimum of 1 window.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata(BaseModel):
    location: Optional[str] = Field(
        None,
        description='The location of the node, if different from instance location.',
    )
    nodeId: Optional[str] = Field(
        None,
        description='The id of the node. This should be equal to SaasInstanceNode.node_id.',
    )
    perSliEligibility: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility
    ] = Field(
        None,
        description='If present, this will override eligibility for the node coming from instance or exclusions for specified SLIs.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata(BaseModel):
    nodes: Optional[
        List[GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata]
    ] = Field(
        None,
        description='Optional. List of nodes. Some producers need to use per-node metadata to calculate SLO. This field allows such producers to publish per-node SLO meta data, which will be consumed by SSA Eligibility Exporter and published in the form of per node metric to Monarch.',
    )
    perSliEligibility: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility
    ] = Field(
        None,
        description='Optional. Multiple per-instance SLI eligibilities which apply for individual SLIs.',
    )
    tier: Optional[str] = Field(
        None,
        description='Name of the SLO tier the Instance belongs to. This name will be expected to match the tiers specified in the service SLO configuration. Field is mandatory and must not be empty.',
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class MaintenanceWindow(BaseModel):
    dailyCycle: Optional[DailyCycle] = Field(None, description='Daily cycle.')
    weeklyCycle: Optional[WeeklyCycle] = Field(None, description='Weekly cycle.')


class UpdatePolicy(BaseModel):
    channel: Optional[Channel] = Field(
        None, description='Optional. Relative scheduling channel applied to resource.'
    )
    denyMaintenancePeriods: Optional[List[DenyMaintenancePeriod]] = Field(
        None,
        description='Deny Maintenance Period that is applied to resource to indicate when maintenance is forbidden. User can specify zero or more non-overlapping deny periods. Maximum number of deny_maintenance_periods expected is one.',
    )
    window: Optional[MaintenanceWindow] = Field(
        None,
        description='Optional. Maintenance window that is applied to resources covered by this policy.',
    )


class MaintenancePolicy(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. The time when the resource was created.'
    )
    description: Optional[str] = Field(
        None,
        description='Optional. Description of what this policy is for. Create/Update methods return INVALID_ARGUMENT if the length is greater than 512.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. Resource labels to represent user provided metadata. Each label is a key-value pair, where both the key and the value are arbitrary strings provided by the user.',
    )
    name: Optional[str] = Field(
        None,
        description='Required. MaintenancePolicy name using the form: `projects/{project_id}/locations/{location_id}/maintenancePolicies/{maintenance_policy_id}` where {project_id} refers to a GCP consumer project ID, {location_id} refers to a GCP region/zone, {maintenance_policy_id} must be 1-63 characters long and match the regular expression `[a-z0-9]([-a-z0-9]*[a-z0-9])?`.',
    )
    state: Optional[State3] = Field(
        None, description='Optional. The state of the policy.'
    )
    updatePolicy: Optional[UpdatePolicy] = Field(
        None, description='Maintenance policy applicable to instance update.'
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. The time when the resource was updated.'
    )


class GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings(BaseModel):
    exclude: Optional[bool] = Field(
        None,
        description='Optional. Exclude instance from maintenance. When true, rollout service will not attempt maintenance on the instance. Rollout service will include the instance in reported rollout progress as not attempted.',
    )
    isRollback: Optional[bool] = Field(
        None,
        description='Optional. If the update call is triggered from rollback, set the value as true.',
    )
    maintenancePolicies: Optional[Dict[str, MaintenancePolicy]] = Field(
        None,
        description='Optional. The MaintenancePolicies that have been attached to the instance. The key must be of the type name of the oneof policy name defined in MaintenancePolicy, and the embedded policy must define the same policy type. For details, please refer to go/cloud-saas-mw-ug. Should not be set if maintenance_policy_names is set. If only the name is needed, then only populate MaintenancePolicy.name.',
    )


class GoogleCloudSaasacceleratorManagementProvidersV1Instance(BaseModel):
    consumerDefinedName: Optional[str] = Field(
        None,
        description='consumer_defined_name is the name of the instance set by the service consumers. Generally this is different from the `name` field which reperesents the system-assigned id of the instance which the service consumers do not recognize. This is a required field for tenants onboarding to Maintenance Window notifications (go/slm-rollout-maintenance-policies#prerequisites).',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. Timestamp when the resource was created.'
    )
    instanceType: Optional[str] = Field(
        None,
        description="Optional. The instance_type of this instance of format: projects/{project_number}/locations/{location_id}/instanceTypes/{instance_type_id}. Instance Type represents a high-level tier or SKU of the service that this instance belong to. When enabled(eg: Maintenance Rollout), Rollout uses 'instance_type' along with 'software_versions' to determine whether instance needs an update or not.",
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. Resource labels to represent user provided metadata. Each label is a key-value pair, where both the key and the value are arbitrary strings provided by the user.',
    )
    maintenancePolicyNames: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. The MaintenancePolicies that have been attached to the instance. The key must be of the type name of the oneof policy name defined in MaintenancePolicy, and the referenced policy must define the same policy type. For details, please refer to go/cloud-saas-mw-ug. Should not be set if maintenance_settings.maintenance_policies is set.',
    )
    maintenanceSchedules: Optional[
        Dict[str, GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule]
    ] = Field(
        None,
        description='The MaintenanceSchedule contains the scheduling information of published maintenance schedule with same key as software_versions.',
    )
    maintenanceSettings: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings
    ] = Field(
        None, description='Optional. The MaintenanceSettings associated with instance.'
    )
    name: Optional[str] = Field(
        None,
        description='Unique name of the resource. It uses the form: `projects/{project_number}/locations/{location_id}/instances/{instance_id}` Note: This name is passed, stored and logged across the rollout system. So use of consumer project_id or any other consumer PII in the name is strongly discouraged for wipeout (go/wipeout) compliance. See go/elysium/project_ids#storage-guidance for more details.',
    )
    notificationParameters: Optional[
        Dict[str, GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter]
    ] = Field(
        None,
        description='Optional. notification_parameter are information that service producers may like to include that is not relevant to Rollout. This parameter will only be passed to Gamma and Cloud Logging for notification/logging purpose.',
    )
    producerMetadata: Optional[Dict[str, str]] = Field(
        None,
        description='Output only. Custom string attributes used primarily to expose producer-specific information in monitoring dashboards. See go/get-instance-metadata.',
    )
    provisionedResources: Optional[
        List[GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource]
    ] = Field(
        None,
        description='Output only. The list of data plane resources provisioned for this instance, e.g. compute VMs. See go/get-instance-metadata.',
    )
    slmInstanceTemplate: Optional[str] = Field(
        None,
        description="Link to the SLM instance template. Only populated when updating SLM instances via SSA's Actuation service adaptor. Service producers with custom control plane (e.g. Cloud SQL) doesn't need to populate this field. Instead they should use software_versions.",
    )
    sloMetadata: Optional[
        GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata
    ] = Field(
        None,
        description='Output only. SLO metadata for instance classification in the Standardized dataplane SLO platform. See go/cloud-ssa-standard-slo for feature description.',
    )
    softwareVersions: Optional[Dict[str, str]] = Field(
        None,
        description='Software versions that are used to deploy this instance. This can be mutated by rollout services.',
    )
    state: Optional[State1] = Field(
        None,
        description="Output only. Current lifecycle state of the resource (e.g. if it's being created or ready to use).",
    )
    tenantProjectId: Optional[str] = Field(
        None,
        description='Output only. ID of the associated GCP tenant project. See go/get-instance-metadata.',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. Timestamp when the resource was last modified.'
    )
